version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: crud
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - 3308:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql